# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 17:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Legislation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('hr', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Representative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('district', models.CharField(max_length=140)),
                ('state', models.CharField(max_length=140)),
                ('party', models.CharField(choices=[('D', 'Democrat'), ('R', 'Republican')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='SuperPAC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.IntegerField()),
                ('legislation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Legislation')),
                ('representative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Representative')),
            ],
        ),
        migrations.AddField(
            model_name='donation',
            name='represenative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Representative'),
        ),
        migrations.AddField(
            model_name='donation',
            name='superpac',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.SuperPAC'),
        ),
    ]
