# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='legislation',
            name='sitelink',
            field=models.CharField(default='https://www.wikipedia.org/', max_length=500),
        ),
        migrations.AddField(
            model_name='representative',
            name='sitelink',
            field=models.CharField(default='https://www.wikipedia.org/', max_length=500),
        ),
        migrations.AddField(
            model_name='superpac',
            name='sitelink',
            field=models.CharField(default='https://www.wikipedia.org/', max_length=500),
        ),
    ]
