# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170322_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='legislation',
            name='fecid',
            field=models.CharField(default='1', max_length=9),
        ),
        migrations.AddField(
            model_name='legislation',
            name='propublicaid',
            field=models.CharField(default='1', max_length=9),
        ),
        migrations.AddField(
            model_name='representative',
            name='fecid',
            field=models.CharField(default='1', max_length=9),
        ),
        migrations.AddField(
            model_name='representative',
            name='propublicaid',
            field=models.CharField(default='1', max_length=9),
        ),
        migrations.AddField(
            model_name='superpac',
            name='fecid',
            field=models.CharField(default='1', max_length=9),
        ),
        migrations.AddField(
            model_name='superpac',
            name='propublicaid',
            field=models.CharField(default='1', max_length=9),
        ),
    ]
